<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\Schema;

class KaryawanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employeesData = [
            [
                'emp_Code' => 'EMP001',
                'emp_NID' => 'NID001',
                'emp_Name' => 'John Doe',
                'emp_ActiveYN' => 'Y',
                'emp_Address' => 'Jl. Merdeka No.1',
                'emp_CityCode' => 'CT001',
                'emp_ProvinceCode' => 'PR001',
                'emp_ZipCode' => '12345',
                'emp_Phone1' => '021111111',
                'emp_hp1' => '0811111111',
                'emp_Email' => 'john@example.com',
                'emp_Sex' => 'M',
                'emp_Marital' => 'S',
                'emp_Religion' => 'Islam',
                'emp_PlaceBorn' => 'Jakarta',
                'emp_DateBorn' => '1990-01-01',
                'emp_Enroll' => '2020-01-01',
                'emp_startcontract' => '2020-01-01',
                'emp_Expired' => '2023-12-31',
                'emp_permanent' => null,
                'emp_office' => 'OF01',
                'emp_ptkp' => 'TK0',
                'emp_blood' => 'O',
                'EMP_SHIF' => 'S1',
                'EMP_PAJAK' => '01',
                'EMP_status' => 'FT',
                'emp_bayar' => '01',
                'emp_BANK' => 'BNI',
                'emp_NOREK' => '1234567890',
                'emp_PEMILIK' => 'John Doe',
                'emp_NPWP' => '01.234.567.8-999.000',
                'emp_education' => 'S1',
                'EMP_JAMSOSTEK' => 'BPJS001',
                'emp_datejamsostek' => '2020-02-01',
                'emp_ktp' => '01',
                'emp_no_ktp' => '3173020101010001',
                'emp_ENTRYID' => '1',
                'emp_FirstEntry' => now(),
            ],
            [
                'emp_Code' => 'EMP002',
                'emp_NID' => 'NID002',
                'emp_Name' => 'Jane Smith',
                'emp_ActiveYN' => 'Y',
                'emp_Address' => 'Jl. Sudirman No.5',
                'emp_CityCode' => 'CT002',
                'emp_ProvinceCode' => 'PR002',
                'emp_ZipCode' => '54321',
                'emp_Phone1' => '021222222',
                'emp_hp1' => '0812222222',
                'emp_Email' => 'jane@example.com',
                'emp_Sex' => 'F',
                'emp_Marital' => 'M',
                'emp_Religion' => 'Kristen',
                'emp_PlaceBorn' => 'Bandung',
                'emp_DateBorn' => '1988-02-02',
                'emp_Enroll' => '2019-02-01',
                'emp_startcontract' => '2019-02-01',
                'emp_Expired' => '2022-12-31',
                'emp_permanent' => null,
                'emp_office' => 'OF02',
                'emp_ptkp' => 'TK0',
                'emp_blood' => 'A',
                'EMP_SHIF' => 'S2',
                'EMP_PAJAK' => '01',
                'EMP_status' => 'FT',
                'emp_bayar' => '01',
                'emp_BANK' => 'BCA',
                'emp_NOREK' => '0987654321',
                'emp_PEMILIK' => 'Jane Smith',
                'emp_NPWP' => '02.345.678.9-888.000',
                'emp_education' => 'S2',
                'EMP_JAMSOSTEK' => 'BPJS002',
                'emp_datejamsostek' => '2019-03-01',
                'emp_ktp' => '01',
                'emp_no_ktp' => '3273020202020002',
                'emp_ENTRYID' => '1',
                'emp_FirstEntry' => now(),
            ],
            [
                'emp_Code' => 'EMP003',
                'emp_NID' => 'NID003',
                'emp_Name' => 'Michael Jordan',
                'emp_ActiveYN' => 'Y',
                'emp_Address' => 'Jl. Melati No.10',
                'emp_CityCode' => 'CT003',
                'emp_ProvinceCode' => 'PR003',
                'emp_ZipCode' => '23456',
                'emp_Phone1' => '021333333',
                'emp_hp1' => '0813333333',
                'emp_Email' => 'mj@example.com',
                'emp_Sex' => 'M',
                'emp_Marital' => 'S',
                'emp_Religion' => 'Katolik',
                'emp_PlaceBorn' => 'Surabaya',
                'emp_DateBorn' => '1992-03-03',
                'emp_Enroll' => '2021-03-01',
                'emp_startcontract' => '2021-03-01',
                'emp_Expired' => '2024-02-28',
                'emp_permanent' => null,
                'emp_office' => 'OF01',
                'emp_ptkp' => 'TK0',
                'emp_blood' => 'B',
                'EMP_SHIF' => 'S1',
                'EMP_PAJAK' => '01',
                'EMP_status' => 'FT',
                'emp_bayar' => '01',
                'emp_BANK' => 'Mandiri',
                'emp_NOREK' => '1122334455',
                'emp_PEMILIK' => 'Michael Jordan',
                'emp_NPWP' => '03.456.789.0-777.000',
                'emp_education' => 'S1',
                'EMP_JAMSOSTEK' => 'BPJS003',
                'emp_datejamsostek' => '2021-04-01',
                'emp_ktp' => '01',
                'emp_no_ktp' => '3373020303030003',
                'emp_ENTRYID' => '1',
                'emp_FirstEntry' => now(),
            ],
            [
                'emp_Code' => 'EMP004',
                'emp_NID' => 'NID004',
                'emp_Name' => 'Alice Wonderland',
                'emp_ActiveYN' => 'Y',
                'emp_Address' => 'Jl. Mawar No.15',
                'emp_CityCode' => 'CT004',
                'emp_ProvinceCode' => 'PR004',
                'emp_ZipCode' => '34567',
                'emp_Phone1' => '021444444',
                'emp_hp1' => '0814444444',
                'emp_Email' => 'alice@example.com',
                'emp_Sex' => 'F',
                'emp_Marital' => 'S',
                'emp_Religion' => 'Hindu',
                'emp_PlaceBorn' => 'Medan',
                'emp_DateBorn' => '1995-04-04',
                'emp_Enroll' => '2022-04-01',
                'emp_startcontract' => '2022-04-01',
                'emp_Expired' => '2025-03-31',
                'emp_permanent' => null,
                'emp_office' => 'OF02',
                'emp_ptkp' => 'TK0',
                'emp_blood' => 'O',
                'EMP_SHIF' => 'S1',
                'EMP_PAJAK' => '01',
                'EMP_status' => 'FT',
                'emp_bayar' => '01',
                'emp_BANK' => 'BRI',
                'emp_NOREK' => '5566778899',
                'emp_PEMILIK' => 'Alice Wonderland',
                'emp_NPWP' => '04.567.890.1-666.000',
                'emp_education' => 'S1',
                'EMP_JAMSOSTEK' => 'BPJS004',
                'emp_datejamsostek' => '2022-05-01',
                'emp_ktp' => '01',
                'emp_no_ktp' => '3473020404040004',
                'emp_ENTRYID' => '1',
                'emp_FirstEntry' => now(),
            ],
            [
                'emp_Code' => 'EMP005',
                'emp_NID' => 'NID005',
                'emp_Name' => 'Bob Builder',
                'emp_ActiveYN' => 'Y',
                'emp_Address' => 'Jl. Kenanga No.20',
                'emp_CityCode' => 'CT005',
                'emp_ProvinceCode' => 'PR005',
                'emp_ZipCode' => '45678',
                'emp_Phone1' => '021555555',
                'emp_hp1' => '0815555555',
                'emp_Email' => 'bob@example.com',
                'emp_Sex' => 'M',
                'emp_Marital' => 'M',
                'emp_Religion' => 'Budha',
                'emp_PlaceBorn' => 'Yogyakarta',
                'emp_DateBorn' => '1987-05-05',
                'emp_Enroll' => '2018-05-01',
                'emp_startcontract' => '2018-05-01',
                'emp_Expired' => '2021-04-30',
                'emp_permanent' => null,
                'emp_office' => 'OF01',
                'emp_ptkp' => 'TK0',
                'emp_blood' => 'A',
                'emp_education' => 'D3',
                'EMP_SHIF' => '01',
                'EMP_status' => 'FT',
                'emp_bayar' => '01',
                'emp_BANK' => 'CIMB',
                'emp_NOREK' => '6677889900',
                'emp_PEMILIK' => 'Bob Builder',
                'emp_NPWP' => '05.678.901.2-555.000',
                'EMP_PAJAK' => '01',
                'EMP_JAMSOSTEK' => 'BPJS005',
                'emp_datejamsostek' => '2018-06-01',
                'emp_ktp' => '01',
                'emp_no_ktp' => '3573020505050005',
                'emp_ENTRYID' => '1',
                'emp_FirstEntry' => now(),
            ],
            [
                'emp_Code' => 'EMP006',
                'emp_NID' => 'NID006',
                'emp_Name' => 'Charlie Chaplin',
                'emp_ActiveYN' => 'Y',
                'emp_Address' => 'Jl. Anggrek No.25',
                'emp_CityCode' => 'CT006',
                'emp_ProvinceCode' => 'PR006',
                'emp_ZipCode' => '56789',
                'emp_Phone1' => '021666666',
                'emp_hp1' => '0816666666',
                'emp_Email' => 'charlie@example.com',
                'emp_Sex' => 'M',
                'emp_Marital' => 'S',
                'emp_Religion' => 'Konghucu',
                'emp_PlaceBorn' => 'Semarang',
                'emp_DateBorn' => '1985-06-06',
                'emp_Enroll' => '2017-06-01',
                'emp_startcontract' => '2017-06-01',
                'emp_Expired' => '2020-05-31',
                'emp_permanent' => null,
                'emp_office' => 'OF02',
                'emp_ptkp' => 'TK0',
                'emp_blood' => 'B',
                'EMP_SHIF' => 'SMA',
                'EMP_PAJAK' => '01',
                'EMP_status' => 'FT',
                'emp_bayar' => '01',
                'emp_BANK' => 'BSI',
                'emp_NOREK' => '7788990011',
                'emp_PEMILIK' => 'Charlie Chaplin',
                'emp_NPWP' => '06.789.012.3-444.000',
                'emp_education' => 'SMA',
                'EMP_JAMSOSTEK' => 'BPJS006',
                'emp_datejamsostek' => '2017-07-01',
                'emp_ktp' => '01',
                'emp_no_ktp' => '3673020606060006',
                'emp_ENTRYID' => '1',
                'emp_FirstEntry' => now(),
            ],
            [
                'emp_Code' => 'EMP007',
                'emp_NID' => 'NID007',
                'emp_Name' => 'Diana Prince',
                'emp_ActiveYN' => 'Y',
                'emp_Address' => 'Jl. Flamboyan No.30',
                'emp_CityCode' => 'CT007',
                'emp_ProvinceCode' => 'PR007',
                'emp_ZipCode' => '67890',
                'emp_Phone1' => '021777777',
                'emp_hp1' => '0817777777',
                'emp_Email' => 'diana@example.com',
                'emp_Sex' => 'F',
                'emp_Marital' => 'M',
                'emp_Religion' => 'Islam',
                'emp_PlaceBorn' => 'Makassar',
                'emp_DateBorn' => '1991-07-07',
                'emp_Enroll' => '2020-07-01',
                'emp_startcontract' => '2020-07-01',
                'emp_Expired' => '2023-06-30',
                'emp_permanent' => null,
                'emp_office' => 'OF01',
                'emp_ptkp' => 'TK0',
                'emp_blood' => 'O',
                'EMP_SHIF' => 'S2',
                'EMP_PAJAK' => '01',
                'EMP_status' => 'FT',
                'emp_bayar' => '01',
                'emp_BANK' => 'BTN',
                'emp_NOREK' => '8899001122',
                'emp_PEMILIK' => 'Diana Prince',
                'emp_NPWP' => '07.890.123.4-333.000',
                'emp_education' => 'S2',
                'EMP_JAMSOSTEK' => 'BPJS007',
                'emp_datejamsostek' => '2020-08-01',
                'emp_ktp' => '01',
                'emp_no_ktp' => '3773020707070007',
                'emp_ENTRYID' => '1',
                'emp_FirstEntry' => now(),
            ],
            [
                'emp_Code' => 'EMP008',
                'emp_NID' => 'NID008',
                'emp_Name' => 'Eddie Brock',
                'emp_ActiveYN' => 'Y',
                'emp_Address' => 'Jl. Sakura No.35',
                'emp_CityCode' => 'CT008',
                'emp_ProvinceCode' => 'PR008',
                'emp_ZipCode' => '78901',
                'emp_Phone1' => '021888888',
                'emp_hp1' => '0818888888',
                'emp_Email' => 'eddie@example.com',
                'emp_Sex' => 'M',
                'emp_Marital' => 'S',
                'emp_Religion' => 'Kristen',
                'emp_PlaceBorn' => 'Palembang',
                'emp_DateBorn' => '1993-08-08',
                'emp_Enroll' => '2021-08-01',
                'emp_startcontract' => '2021-08-01',
                'emp_Expired' => '2024-07-31',
                'emp_permanent' => null,
                'emp_office' => 'OF02',
                'emp_ptkp' => 'TK0',
                'emp_blood' => 'A',
                'EMP_SHIF' => 'S1',
                'EMP_PAJAK' => '01',
                'EMP_status' => 'FT',
                'emp_bayar' => '01',
                'emp_BANK' => 'Bank Jatim',
                'emp_NOREK' => '9900112233',
                'emp_PEMILIK' => 'Eddie Brock',
                'emp_NPWP' => '08.901.234.5-222.000',
                'emp_education' => 'S1',
                'EMP_JAMSOSTEK' => 'BPJS008',
                'emp_datejamsostek' => '2021-09-01',
                'emp_ktp' => '01',
                'emp_no_ktp' => '3873020808080008',
                'emp_ENTRYID' => '1',
                'emp_FirstEntry' => now(),
            ],
            [
                'emp_Code' => 'EMP009',
                'emp_NID' => 'NID009',
                'emp_Name' => 'Fiona Shrek',
                'emp_ActiveYN' => 'Y',
                'emp_Address' => 'Jl. Dahlia No.40',
                'emp_CityCode' => 'CT009',
                'emp_ProvinceCode' => 'PR009',
                'emp_ZipCode' => '89012',
                'emp_Phone1' => '021999999',
                'emp_hp1' => '0819999999',
                'emp_Email' => 'fiona@example.com',
                'emp_Sex' => 'F',
                'emp_Marital' => 'M',
                'emp_Religion' => 'Katolik',
                'emp_PlaceBorn' => 'Balikpapan',
                'emp_DateBorn' => '1994-09-09',
                'emp_Enroll' => '2022-09-01',
                'emp_startcontract' => '2022-09-01',
                'emp_Expired' => '2025-08-31',
                'emp_permanent' => null,
                'emp_office' => 'OF01',
                'emp_ptkp' => 'TK0',
                'emp_blood' => 'B',
                'EMP_SHIF' => 'S1',
                'EMP_PAJAK' => '01',
                'EMP_status' => 'FT',
                'emp_bayar' => '01',
                'emp_BANK' => 'OCBC',
                'emp_NOREK' => '0011223344',
                'emp_PEMILIK' => 'Fiona Shrek',
                'emp_NPWP' => '09.012.345.6-111.000',
                'emp_education' => 'D3',
                'EMP_JAMSOSTEK' => 'BPJS009',
                'emp_datejamsostek' => '2022-10-01',
                'emp_ktp' => '01',
                'emp_no_ktp' => '3973020909090009',
                'emp_ENTRYID' => '1',
                'emp_FirstEntry' => now(),
            ],
            [
                'emp_Code' => 'EMP010',
                'emp_NID' => 'NID010',
                'emp_Name' => 'Gordon Freeman',
                'emp_ActiveYN' => 'Y',
                'emp_Address' => 'Jl. Tulip No.45',
                'emp_CityCode' => 'CT010',
                'emp_ProvinceCode' => 'PR010',
                'emp_ZipCode' => '90123',
                'emp_Phone1' => '022111111',
                'emp_hp1' => '0821111111',
                'emp_Email' => 'gordon@example.com',
                'emp_Sex' => 'M',
                'emp_Marital' => 'S',
                'emp_Religion' => 'Islam',
                'emp_PlaceBorn' => 'Pontianak',
                'emp_DateBorn' => '1989-10-10',
                'emp_Enroll' => '2016-10-01',
                'emp_startcontract' => '2016-10-01',
                'emp_Expired' => '2019-09-30',
                'emp_permanent' => null,
                'emp_office' => 'OF02',
                'emp_ptkp' => 'TK0',
                'emp_blood' => 'O',
                'EMP_SHIF' => 'S1',
                'EMP_PAJAK' => '01',
                'EMP_status' => 'FT',
                'emp_bayar' => '01',
                'emp_BANK' => 'Permata',
                'emp_NOREK' => '1122334455',
                'emp_PEMILIK' => 'Gordon Freeman',
                'emp_NPWP' => '10.123.456.7-000.000',
                'emp_education' => 'S2',
                'EMP_JAMSOSTEK' => 'BPJS010',
                'emp_datejamsostek' => '2016-11-01',
                'emp_ktp' => '01',
                'emp_no_ktp' => '4073021010100010',
                'emp_ENTRYID' => '1',
                'emp_FirstEntry' => now(),
            ],
        ];

        // Loop melalui data untuk menambahkan password yang di-hash
        $processedData = array_map(function ($employee) {
            // Ambil tanggal lahir dan format menjadi ddmmyyyy
            $passwordString = Carbon::parse($employee['emp_DateBorn'])->format('dmY');
            
            // Menggunakan nama kolom 'emp_password' yang benar
            $employee['emp_password'] = Hash::make($passwordString);
            
            return $employee;
        }, $employeesData);

        // PERBAIKAN: Nonaktifkan pengecekan foreign key sebelum truncate
        Schema::disableForeignKeyConstraints();
        
        // Hapus data lama sebelum memasukkan yang baru untuk menghindari duplikasi
        DB::table('m_employee')->truncate();

        // PERBAIKAN: Aktifkan kembali pengecekan foreign key setelah truncate
        Schema::enableForeignKeyConstraints();

        // Masukkan data yang sudah diproses ke dalam database
        DB::table('m_employee')->insert($processedData);
    }
}
